### ISSUE TITLE
Logo design idea

### ISSUE THREAD

**Issue by gcollazo** [commonwealth-of-puerto-rico/libre#11]
Llevo bastante tiempo pensando en ideas de logo para este proyecto y finalmente hoy (inspirado por [requests](http://docs.python-requests.org/en/latest/)) me decidí a ejecutar una de ellas. El diseño esta basado en un [dibujo](http://imgur.com/y0Gr782) "public domain" que encontré. ¿Que les parece?

**Archivos**
[libre-logo.ai](https://dl.dropboxusercontent.com/u/1364069/libre-logo.ai)
[libre-logo.svg](https://dl.dropboxusercontent.com/u/1364069/libre-logo.svg)
[libre-logo.png](https://dl.dropboxusercontent.com/u/1364069/libre-logo.png)

**Preview**
![libre-logo](https://f.cloud.github.com/assets/61048/1894640/ee1ab48e-7af4-11e3-8ba3-ee100f431639.png)

**Comment by Mauronx13** [comment]
Buen concepto para el logo. 

Creo que es una buena idea.

**Comment by gcollazo** [comment]
Closing
