### ISSUE TITLE
inotify is not available on macosx-10.8-intel

### ISSUE THREAD

**Issue by ran-research-lab** [commonwealth-of-puerto-rico/libre#2]
Any recommendations on how to overcome the following issue?: 

```
 inotify is not available on macosx-10.8-intel
```

(without having to change the OS)

Saludos,
Rafael Arce

**Comment by ghost** [comment]
I've been looking at python-watchdog as a cross-platform alternative. (http://pythonhosted.org/watchdog/installation.html#supported-platforms-and-caveats)

**Comment by ghost** [comment]
python-watchdog and the related approach only worked for file based sources, since LIBRE now support web services, REST APIs and URL based sources a generic scheduler approach was coded instead removing the need for filesystem monitoring.
